# 开发环境配置 - 支持热重载
version: "3.8"

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8001
    depends_on:
      - backend-dev
    networks:
      - feednews-network

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_SERVER=localhost
      - POSTGRES_USER=saieng
      - POSTGRES_PASSWORD=yang1234
      - POSTGRES_DB=feedNew
      - DATABASE_URL=postgresql+asyncpg://saieng:yang1234@db:5432/feedNew
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - PROJECT_NAME=FeedNews
      - API_V1_STR=/api/v1
    depends_on:
      - db
    networks:
      - feednews-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=saieng
      - POSTGRES_PASSWORD=yang1234
      - POSTGRES_DB=feedNew
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - feednews-network

volumes:
  postgres_data:

networks:
  feednews-network:
    driver: bridge
