# 开发环境配置 - 支持热重载
version: "3.8"

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8001
    depends_on:
      - backend-dev
    networks:
      - feednews-network

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - feednews-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - feednews-network

volumes:
  postgres_data:

networks:
  feednews-network:
    driver: bridge
